name: Metrics
on:
  schedule: [{cron: "*/15 * * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: minhh2792
          template: classic
          base: header, activity, community, repositories, metadata
          config_display: columns
          config_timezone: Asia/Bangkok
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
        
          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_mode: top
          plugin_music_top_type: tracks 
          plugin_music_time_range: short
          plugin_music_token: ${{ secrets.SPOTIFY_TOKEN }}
          plugin_music_limit: 4
          
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          
          plugin_notable: yes
          plugin_notable_from: organization
          plugin_notable_types: commit
