name: Metrics
on:
  schedule: [{cron: "*/15 * * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Left
        uses: lowlighter/metrics@latest
        with:
          filename: left.github.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: minhh2792
          template: classic
          base: header
          plugin_lines: yes
          config_order: base.header, isocalendar, languages, topics, notable achievements
          
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
          plugin_languages: yes
          plugin_languages_ignored: 
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 4
          
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons
          
          plugin_notable: yes
          plugin_notable_from: organization
          plugin_notable_types: commit
          
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          
      - name: Right
        uses: lowlighter/metrics@latest
        with:
          filename: right.github.svg
          token: NOT_NEEDED
          committer_token: ${{ secrets.METRICS_TOKEN }}
        
          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_mode: top
          plugin_music_top_type: tracks 
          plugin_music_time_range: short
          plugin_music_token: ${{ secrets.SPOTIFY_TOKEN }}
          plugin_music_limit: 8
