name: Right
on:
  schedule: [{cron: "*/15 * * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Right
        uses: lowlighter/metrics@latest
        with:
          filename: right.github.svg
          token: NOT_NEEDED
          committer_token: ${{ secrets.GITHUB_TOKEN }}
        
          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_mode: top
          plugin_music_top_type: tracks 
          plugin_music_time_range: short
          plugin_music_token: ${{ secrets.SPOTIFY_TOKEN }}
          plugin_music_limit: 4
          
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          
          config_order: music, achievements
